# Generated by Django 3.2.8 on 2021-12-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_category',
            field=models.CharField(default='', max_length=30),
        ),
    ]
